#
# Makefile
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	test1.pdf test2.pdf test3.pdf

test1.pdf:	test1.tex
	TEXINPUTS=:../buch pdflatex test1.tex

test2.pdf:	test2.tex
	TEXINPUTS=:../buch pdflatex test2.tex

test3.pdf:	test3.tex
	TEXINPUTS=:../buch pdflatex test3.tex


