#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-logistic =						\
	papers/logistic/packages.tex					\
	papers/logistic/main.tex					\
	papers/logistic/references.bib				\
	papers/logistic/einleitung.tex				\
	papers/logistic/problemstellung.tex				\
	papers/logistic/loesung.tex					\
	papers/logistic/folgerungen.tex

