#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-pade =						\
	papers/pade/packages.tex					\
	papers/pade/main.tex					\
	papers/pade/references.bib				\
	papers/pade/einleitung.tex				\
	papers/pade/problemstellung.tex				\
	papers/pade/loesung.tex					\
	papers/pade/folgerungen.tex

