#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-perturbation =						\
	papers/perturbation/packages.tex					\
	papers/perturbation/main.tex					\
	papers/perturbation/references.bib				\
	papers/perturbation/einleitung.tex				\
	papers/perturbation/problemstellung.tex				\
	papers/perturbation/loesung.tex					\
	papers/perturbation/folgerungen.tex

