#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-arctan =							\
	papers/arctan/packages.tex					\
	papers/arctan/main.tex						\
	papers/arctan/references.bib

