#
# Makefile
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	sirI0path.tex

sirpath.tex:	sir.m
	octave sir.m

sirbetapath.tex:	sirbeta.m
	octave --quiet sirbeta.m

sirI0path.tex:	sirI0.m
	octave --quiet sirI0.m

i0.tex:	i0.m
	octave --quiet i0.m
