#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-interdiff =						\
	papers/interdiff/packages.tex					\
	papers/interdiff/main.tex					\
	papers/interdiff/problem.tex					\
	papers/interdiff/interpolation.tex				\
	papers/interdiff/ableitung.tex					\
	papers/interdiff/references.bib

