#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-qr =						\
	papers/qr/packages.tex					\
	papers/qr/main.tex					\
	papers/qr/references.bib				\
	papers/qr/einleitung.tex				\
	papers/qr/problemstellung.tex				\
	papers/qr/loesung.tex					\
	papers/qr/folgerungen.tex

