#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-kettenbruch =						\
	papers/kettenbruch/packages.tex					\
	papers/kettenbruch/main.tex					\
	papers/kettenbruch/references.bib				\
	papers/kettenbruch/einleitung.tex				\
	papers/kettenbruch/problemstellung.tex				\
	papers/kettenbruch/rationalezahlen.tex				\
	papers/kettenbruch/irrationalezahlen.tex			\
	papers/kettenbruch/approximation.tex				\
	papers/kettenbruch/folgerungen.tex

