#
# Makefile -- make file for the paper kettenbruch
#
# (c) 2020 Prof Dr Andreas Mueller
#

kettenbruch.pdf:	kettenbruch.tex					\
	einleitung.tex rationalezahlen.tex irrationalezahlen.tex	\
	approximation.tex folgerungen.tex references.bib
	pdflatex kettenbruch.tex

images:
	@echo "no images to be created in kettenbruch"
