#
# Makefile -- Bilder für Kapitel "Gewöhnliche Differentialgleichungen"*
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapeprswil
#
all:	prinzip.pdf euler.pdf relativ.pdf rungekutta.pdf \
	kettenlinie.pdf kettenloesung.pdf grundlagen.pdf \
	ordnung2.pdf

%.pdf:	%.tex
	pdflatex $<
