#
# Makefile -- build images for pde chapter
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
images = derivatives.pdf diffex.pdf diff2.pdf laplace.pdf

all:	$(images)

derivatives.pdf:	derivatives.tex
	pdflatex derivatives.tex

diffex.pdf:	diffex.tex
	pdflatex diffex.tex

diff2.pdf:	diff2.tex
	pdflatex diff2.tex

laplace.pdf:	laplace.tex
	pdflatex laplace.tex

