#
# Makefile -- build images for pde chapter
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
images = derivatives.pdf diffex.pdf diff2.pdf laplace.pdf poisson.pdf \
	neumann.pdf kont.pdf 2dpart.pdf gebiet.pdf offen.pdf

all:	$(images)

derivatives.pdf:	derivatives.tex
	pdflatex derivatives.tex

diffex.pdf:	diffex.tex
	pdflatex diffex.tex

diff2.pdf:	diff2.tex
	pdflatex diff2.tex

laplace.pdf:	laplace.tex
	pdflatex laplace.tex

poisson.pdf:	poisson.tex
	pdflatex poisson.tex

neumann.pdf:	neumann.tex
	pdflatex neumann.tex

kont.pdf:	kont.tex
	pdflatex kont.tex

2dpart.pdf:	2dpart.tex
	pdflatex 2dpart.tex

gebiet.pdf:	gebiet.tex
	pdflatex gebiet.tex

offen.pdf:	offen.tex
	pdflatex offen.tex

