#
# Makefile -- build images for pde chapter
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
images = derivatives.pdf diffex.pdf

all:	$(images)

derivatives.pdf:	derivatives.tex
	pdflatex derivatives.tex

diffex.pdf:	diffex.tex
	pdflatex diffex.tex
