#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-burgers =						\
	papers/burgers/packages.tex					\
	papers/burgers/main.tex					\
	papers/burgers/references.bib				\
	papers/burgers/einleitung.tex				\
	papers/burgers/problemstellung.tex				\
	papers/burgers/loesung.tex					\
	papers/burgers/folgerungen.tex

