#
# Makefile -- generate TikZ images
#
# (c) 2020
#
all:	matrizen.pdf dreiecke.pdf gross.pdf


matrizen.pdf:	matrizen.tex
	pdflatex matrizen.tex

dreiecke.pdf:	dreiecke.tex
	pdflatex dreiecke.tex

gross.pdf:	gross.tex
	pdflatex gross.tex

