#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-laplace =						\
	papers/laplace/packages.tex					\
	papers/laplace/main.tex					\
	papers/laplace/references.bib				\
	papers/laplace/einleitung.tex				\
	papers/laplace/problemstellung.tex				\
	papers/laplace/loesung.tex					\
	papers/laplace/folgerungen.tex

