#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-vanderpol =						\
	papers/vanderpol/packages.tex					\
	papers/vanderpol/main.tex					\
	papers/vanderpol/references.bib				\
	papers/vanderpol/einleitung.tex				\
	papers/vanderpol/loesung.tex					\
	papers/vanderpol/folgerungen.tex

