#
# Makefile -- Graphik für numerische Berechnung einer Funktion mit starker
#             Auslöschung
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#

numerisch.pdf:	numerisch.tex path.tex
	pdflatex numerisch.tex
