#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-quadratur =						\
	papers/quadratur/packages.tex					\
	papers/quadratur/main.tex					\
	papers/quadratur/references.bib				\
	papers/quadratur/einleitung.tex				\
	papers/quadratur/problemstellung.tex				\
	papers/quadratur/loesung.tex					\
	papers/quadratur/folgerungen.tex

