#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-steps =						\
	papers/steps/packages.tex					\
	papers/steps/main.tex					\
	papers/steps/references.bib				\
	papers/steps/einleitung.tex				\
	papers/steps/problemstellung.tex				\
	papers/steps/loesung.tex					\
	papers/steps/folgerungen.tex

