#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-steps =						\
	papers/steps/packages.tex					\
	papers/steps/main.tex					\
	papers/steps/references.bib				\
	papers/steps/einleitung.tex				\
	papers/steps/problemstellung.tex				\
	papers/steps/loesung.tex					\
	papers/steps/folgerungen.tex			\
	\
	papers/steps/img/gravity_different_fixed_stepsize.pdf\
	papers/steps/img/Fehlberg_Flowchart.pdf\
	papers/steps/img/ssc.pdf


