#
# Makefile.inc -- additional depencencies
#
# (c) 20920 Prof Dr Andreas Müller, Hochschule Rapperswil
#
chapter0 =								\
	../slides/0/intro.tex						\
	../slides/0/resourcen.tex					\
	../slides/0/latextipps.tex					\
	../slides/0/themen.tex						\
	../slides/0/chapter.tex

chapter1 =								\
	../slides/1/float.tex						\
	../slides/1/ieee754.tex						\
	../slides/1/ausloeschung.tex					\
	../slides/1/verschmierung.tex					\
	../slides/1/assoziativ.tex					\
	../slides/1/iteration.tex					\
	../slides/1/fixpunktiteration.tex				\
	../slides/1/analyse.tex						\
	../slides/1/chapter.tex

slides = 								\
	$(chapter0) $(chapter1)
