#
# Makefile
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	bromwich.pdf talbot1.pdf talbot2.pdf

bromwich.pdf:	bromwich.tex
	pdflatex bromwich.tex

talbot1.pdf:	talbot1.tex
	pdflatex talbot1.tex

talbot2.pdf:	talbot2.tex
	pdflatex talbot2.tex

