#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-cg =						\
	papers/cg/packages.tex					\
	papers/cg/main.tex					\
	papers/cg/references.bib				\
	papers/cg/steepest_descent.tex				\
	papers/cg/herleitung_algorithmus.tex			\
	papers/cg/ergebnisse.tex				\


