#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-cg =						\
	papers/cg/packages.tex					\
	papers/cg/main.tex					\
	papers/cg/references.bib				\
	papers/cg/einleitung.tex				\
	papers/cg/problemstellung.tex				\
	papers/cg/loesung.tex					\
	papers/cg/folgerungen.tex

