#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-ableitung =						\
	papers/ableitung/packages.tex					\
	papers/ableitung/main.tex					\
	papers/ableitung/references.bib				\
	papers/ableitung/einleitung.tex				\
	papers/ableitung/problemstellung.tex				\
	papers/ableitung/loesung.tex					\
	papers/ableitung/folgerungen.tex

