#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-legendre =						\
	papers/legendre/packages.tex					\
	papers/legendre/main.tex					\
	papers/legendre/references.bib				\
	papers/legendre/einleitung.tex				\
	papers/legendre/problemstellung.tex				\
	papers/legendre/loesung.tex					\
	papers/legendre/folgerungen.tex

