#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-francis =						\
	papers/francis/packages.tex					\
	papers/francis/main.tex					\
	papers/francis/references.bib				\
	papers/francis/einleitung.tex				\
	papers/francis/problemstellung.tex				\
	papers/francis/loesung.tex					\
	papers/francis/folgerungen.tex

