#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-taylor =						\
	papers/taylor/packages.tex					\
	papers/taylor/main.tex					\
	papers/taylor/references.bib				\
	papers/taylor/einleitung.tex				\
	papers/taylor/problemstellung.tex				\
	papers/taylor/loesung.tex					\
	papers/taylor/folgerungen.tex

