#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-ew =						\
	papers/ew/packages.tex					\
	papers/ew/main.tex					\
	papers/ew/references.bib				\
	papers/ew/einleitung.tex				\
	papers/ew/problemstellung.tex				\
	papers/ew/loesung.tex					\
	papers/ew/folgerungen.tex

