#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-perturbation2 =						\
	papers/perturbation2/packages.tex					\
	papers/perturbation2/main.tex					\
	papers/perturbation2/references.bib				\
	papers/perturbation2/einleitung.tex				\
	papers/perturbation2/problemstellung.tex				\
	papers/perturbation2/loesung.tex					\
	papers/perturbation2/folgerungen.tex

