#
# Makefile.inc -- Makefile dependencies
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
# 

CHAPTERFILES =								\
	chapters/part1.tex						\
	chapters/vorwort.tex						\
	chapters/0-einleitung/chapter.tex				\
	chapters/references.bib
