#
# Makefile.inc -- Makefile dependencies
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
# 

CHAPTERFILES =								\
	chapters/part1.tex						\
	chapters/vorwort.tex						\
	chapters/00-einleitung/chapter.tex				\
	chapters/10-arithmetik/chapter.tex				\
	chapters/10-arithmetik/zahlensysteme.tex			\
	chapters/10-arithmetik/effekte.tex				\
	chapters/10-arithmetik/iteration.tex				\
	chapters/10-arithmetik/graphisch.tex				\
	chapters/10-arithmetik/kubisch.tex				\
	chapters/10-arithmetik/instabilitaet.tex			\
	chapters/10-arithmetik/kondition.tex				\
	chapters/10-arithmetik/beschleunigung.tex			\
	chapters/20-gleichungen/chapter.tex				\
	chapters/20-gleichungen/nullstellen.tex				\
	chapters/20-gleichungen/newton.tex				\
	chapters/20-gleichungen/homotopie.tex				\
	chapters/30-interpolation/chapter.tex				\
	chapters/30-interpolation/polynom.tex				\
	chapters/30-interpolation/hermite.tex				\
	chapters/30-interpolation/bary.tex				\
	chapters/30-interpolation/splines.tex				\
	chapters/40-integration/chapter.tex				\
	chapters/40-integration/riemann.tex				\
	chapters/40-integration/romberg.tex				\
	chapters/50-ode/chapter.tex					\
	chapters/50-ode/problemstellung.tex				\
	chapters/50-ode/prinzip.tex					\
	chapters/50-ode/fehler.tex					\
	chapters/50-ode/einschritt.tex					\
	chapters/50-ode/mehrschritt.tex					\
	chapters/50-ode/software.tex					\
	chapters/50-ode/randwert.tex					\
	chapters/60-linsys/chapter.tex					\
	chapters/70-pde/chapter.tex					\
	chapters/80-fourier/chapter.tex



