#
# Makefile.inc -- dependencies for this article
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
dependencies-fem =						\
	papers/fem/packages.tex					\
	papers/fem/main.tex					\
	papers/fem/references.bib				\
	papers/fem/einleitung.tex				\
	papers/fem/problemstellung.tex				\
	papers/fem/loesung.tex					\
	papers/fem/folgerungen.tex

